name: Build

on: [push, pull_request]

env:
    CIBW_ARCHS_MACOS: x86_64 arm64
    CIBW_BEFORE_BUILD_LINUX: "if command -v apk &> /dev/null; then apk add bsd-compat-headers; fi"

jobs:
    build_wheels:
        name: Build wheels on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-22.04, macos-12]
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: true
            - name: Build wheels
              uses: pypa/cibuildwheel@v2.11.2
            - uses: actions/upload-artifact@v3
              with:
                  path: ./wheelhouse/*.whl
    build_sdist:
        name: Build source distribution
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: true
            - name: Build sdist
              run: pipx run build --sdist
            - uses: actions/upload-artifact@v3
              with:
                  path: dist/*.tar.gz
